- README.md
> feat: adding some nice badges

- src/runner/runner.ts
> feat: grouping runners props

- src/runner/runner.ts
> feat: grouping manager props

- src/runner/runner.ts
> feat: export autoscalinggroup

- src/runner/runner.ts
ssm managed policy should not be there at all
Fixes #
> feat: use local var for principal and managed policy

- API.md
- example/src/runner-role.ts
- src/runner/cache.ts
> feat: add runners role append example

- test/runner/runner.test.ts
Replace CDK module which using assert module by assertions module in test section
https://pepperize.atlassian.net/browse/PEP-72
> feat: replace cdk module assert/assertions

- src/runner/cache.ts
- test/runner/__snapshots__/cache.test.ts.snap
- test/runner/cache.test.ts
> fix: bucket length 63 chars maximum

- API.md
- src/runner-configuration/machine-options.ts
https://github.com/pepperize/cdk-autoscaling-gitlab-runner/issues/145
https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/blob/main/drivers/amazonec2/amazonec2.go#L651
https://docs.gitlab.com/runner/configuration/runner_autoscale_aws/#the-runnersmachine-section
> fix: private address only

- src/runner-configuration/configuration-mapper.ts
- test/runner-configuration/__snapshots__/configuration-mapper.test.ts.snap
- test/runner-configuration/configuration-mapper.test.ts
> fix: default autoscaling config

- API.md
- src/runner/manager.ts
- src/runner/network.ts
- test/runner/__snapshots__/runner.test.ts.snap
> fix!: prefer private addresses

- API.md
- src/runner-configuration/machine-options.ts
> feat: add root size, volume type, ebs optimized volume

- API.md
- src/runner-configuration/machine-options.ts
> feat: add keypair name to machine options

- API.md
- src/runner-configuration/configuration-mapper.ts
- src/runner-configuration/machine-options.ts
- test/runner-configuration/__snapshots__/configuration-mapper.test.ts.snap
- test/runner-configuration/configuration-mapper.test.ts
- test/runner/__snapshots__/runner.test.ts.snap
- https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/issues/15
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html
- https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/blob/main/drivers/amazonec2/amazonec2.go#L294-303
> feat: use imds v2 by default for job runner

- src/runner/manager.ts
> fix: fetch ssh-keypair

- API.md
- src/runner/cache.ts
- src/runner/job-runner.ts
- src/runner/manager.ts
- src/runner/network.ts
- src/runner/runner.ts
- test/runner/__snapshots__/cache.test.ts.snap
- test/runner/__snapshots__/runner.test.ts.snap
- test/runner/cache.test.ts
- test/runner/runner.test.ts
https://github.com/pepperize/cdk-autoscaling-gitlab-runner/issues/374
Fixes #
> fix: two manager within a stack

- src/runner/manager.ts
- test/runner/__snapshots__/runner.test.ts.snap
> fix(docker-machine): use v0.16.2-gitlab.19 to support docker 23+

- src/runner/manager.ts
- test/runner/__snapshots__/manager.test.ts.snap
- test/runner/__snapshots__/runner.test.ts.snap
`Error creating machine: Error in driver during machine creation: Error launching instance: UnauthorizedOperation: You are not authorized to perform this operation. `
fixes https://github.com/pepperize/cdk-autoscaling-gitlab-runner/issues/537
> fix: remove condition tag value to run instances

- src/runner/manager.ts
- yarn.lock
- added apt-get update to update the repositoriy on spawning a new gitlab runner
Fixes https://github.com/pepperize/cdk-autoscaling-gitlab-runner/issues/328
> fix: install amazon-ecr-credential-helper fails

- .projen/deps.json
- .projenrc.ts
- package.json
- test/runner/__snapshots__/manager.test.ts.snap
- test/runner/__snapshots__/runner.test.ts.snap
- yarn.lock
> chore: bump security group name
